create table users(
      username varchar_ignorecase(50) not null primary key,
      password varchar_ignorecase(100) not null,
      enabled boolean not null);

create table authorities (
      username varchar_ignorecase(50) not null,
      authority varchar_ignorecase(50) not null,
      constraint fk_authorities_users foreign key(username) references users(username));
      create unique index ix_auth_username on authorities (username,authority);

create table groups (
  id bigint generated by default as identity(start with 0) primary key,
  group_name varchar_ignorecase(50) not null);

create table group_authorities (
  group_id bigint not null,
  authority varchar(50) not null,
  constraint fk_group_authorities_group foreign key(group_id) references groups(id));

create table group_members (
  id bigint generated by default as identity(start with 0) primary key,
  username varchar(50) not null,
  group_id bigint not null,
  constraint fk_group_members_group foreign key(group_id) references groups(id));

/************************************ INSERTING DATA ***********************************/

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES('user', '$2a$04$ajRN.pKCxIAOPl0GZtVYxujX1Go9O2dICXDGqdWmhK9jB/ivUXgTG' /*passwd1*/, TRUE);
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED) VALUES('admin', '$2a$04$5051aDqHbmjlE3B0vRPrvOZMI/M295JNMRqH.CIb650v/VJI38apO' /*passwd2*/, TRUE);
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES('user', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES('admin', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES('admin', 'ROLE_ADMIN');